name: AutoTool
version: '${project.version}'
main: me.usainsrht.autotool.AutoTool
api-version: '1.13'
author: UsainSrht
description: Automatically change your item to what's best in your hotbar when breaking blocks.
commands:
  autotool:
    description: Toggle autotool.
    usage: /autotool
    permission: autotool.toggle